//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajero
    {
        public int IdCajero { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public int Cantidad { get; set; }
        public decimal Denominacion { get; set; }
    
        public virtual Tipo Tipo { get; set; }
    }
}
